### ISSUE TITLE
Mention of Airbnb

### ISSUE THREAD

**Issue by matason** [phase2/pattern-lab-starter#106]
Hi folks,

Is the "extends: airbnb" intentional here? https://github.com/phase2/pattern-lab-starter/blob/3ab220e117819849e458839b9372ea5be9729f60/.eslintrc.js#L4

**Comment by tjheffner** [comment]
Hello, yes, it is intentional. The airbnb standards for javascript (https://github.com/airbnb/javascript) are widely used and generally accepted as a sane baseline standard. Drupal has adopted them as part of core: https://www.drupal.org/node/2873849

Any rules can be overridden/modified as needed, in that same eslint file, see: https://eslint.org/docs/user-guide/configuring#configuring-rules
