### ISSUE TITLE
Use of _twig-components

### ISSUE THREAD

**Issue by bobbygryzynger** [phase2/pattern-lab-starter#53]
One thing that I don't see touched upon is your startup guide is how to extend Twig within Pattern Lab.

For example, I have created a new Twig filter under `_twig-components` and have been able to compile Pattern Lab with the filter being recognized. However, when I go to my site I find that I get a `Twig_Error_Syntax` error stating that my custom filter cannot be found. 

Is there any additional configuration necessary to get Drupal to recognize custom filters when they are created within Pattern Lab's structure? Perhaps there needs to be another couple of lines added to the theme's `.info.yml` `component-libraries` block? 

I attempted adding the following with no luck:
```yml
  twig_components:
    paths:
      - source/_twig-components
```

and 

```yml
- source/_twig-components/filters
```

**Comment by illepic** [comment]
Thanks @bobbygryzynger, a quick note about the `source/twig_components/` directory:

Since this PL is simulating working within the Drupal world for a number of functions, you'll notice that some of the pre-existing Twig functions in this folder are simply "dummy filters", returning exactly what they are given. For instance, in `source/twig_components/filters/ti.filter.php`:

````php
<?php
// Drupal translate filter
$filter = new Twig_SimpleFilter('t', function ($string) {
  return $string;
});
````

^^ This just returns exactly what it's given because in our PL twig files, we want to be able to `{{ 'Hello world|t }}` and have the native Drupal t filter pick up (when Drupal eventually uses our Twig file.

To reiterate, in PL we're just mocking a few Drupal functions so that when Drupal comes around later, Drupal has the filters/functions it expects to do real Drupal work :)

To address your use-case of writing your own Twig filter that is picked up by Drupal, you'll still need to create a Drupal module that extends `\Twig_Extension` and provides Drupal all the information it needs about your filter. ([Like this](http://leopathu.in/content/create-custom-twig-filter-drupal-8))

So think about PL as the light prototype level that _is not actually using the custom Drupal filters_. Those filters are simply mocked in PL (for now). I'd recommend writing your own Drupal Twig filter module and then tossing either a copy or simplified version in `source/_twig-components/filters`.

**Comment by bobbygryzynger** [comment]
Thanks @illepic, that clears up how the the `_twig-components` directory is intended to be used.
